# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  playidentityservice:
    image: playidentityservice
    build:
      context: .
      dockerfile: src/Play.Identity.Service/Dockerfile
    ports:
      - 5011:5011
